spring:
  application:
    name: dj-facility
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dj_facility?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: jiangjie1
  jpa:
    hibernate:
      ddl-auto: update #配置自动建表：updata:没有表新建，有表更新操作,控制台显示建表语句
    show-sql: true
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: SZ #配置集群名称，也就是机房位置
        namespace: 590ec80f-7690-4899-8954-83f6f97fd8d6 #命名空间：相同命名空间的服务才可以访问
type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8081