spring:
  application:
    name: dj-protal
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 #服务端地址
      discovery:
        cluster-name: SZ #配置集群名称，也就是机房位置
        namespace: 590ec80f-7690-4899-8954-83f6f97fd8d6 #命名空间：相同命名空间的服务才可以访问
        ephemeral: false # 是否是临时实例
server:
  port: 8080