server:
  port: 10011
spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/dj_portal?serverTimezone=GMT%2B8&useSSL=true
#    username: root
#    password: jiangjie1
  main:
    web-application-type: reactive
  application:
    name: dj-gateway
  cloud:
    nacos:
#      server-addr: localhost:8848
      server-addr: 120.78.15.216:8849
      discovery:
        enabled: true # 不开启注册
        cluster-name: SZ #配置集群名称，也就是机房位置
#        namespace: 590ec80f-7690-4899-8954-83f6f97fd8d6 #命名空间：相同命名空间的服务才可以访问
        namespace: 23023ae3-5df4-4234-9c11-54510e1792bd #命名空间：相同命名空间的服务才可以访问
    gateway:
      discovery:
        locator:
          enabled: true
#          predicates:
#            - Path=/api/user/**"
#      routes:
#        - id: dj-portal
#          uri: lb://dj-portal
#          predicates:
#            - Path=/api/portal/**
#          filters:
#            - AddRequestHeader=jiangjie, hahahahah1111
#        - id: dj-facility
#          uri: lb://dj-facility
#          predicates:
#            - Path=/api/facility/**
#        - id: dj-user1
#          uri: lb://dj-user1
#          predicates:
#            - Path=/api/user/**
#      default-filters:
#        - AddRequestHeader=jiangjie, hahahahah2222
debug: true