// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

package com.dj.grpc.routeguide;

public interface FeatureOrBuilder extends
    // @@protoc_insertion_point(interface_extends:routeguide.Feature)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.routeguide.Point location = 2;</code>
   * @return Whether the location field is set.
   */
  boolean hasLocation();
  /**
   * <code>.routeguide.Point location = 2;</code>
   * @return The location.
   */
  Point getLocation();
  /**
   * <code>.routeguide.Point location = 2;</code>
   */
  PointOrBuilder getLocationOrBuilder();
}
