// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

package com.dj.grpc.routeguide;

public interface PointOrBuilder extends
    // @@protoc_insertion_point(interface_extends:routeguide.Point)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 经度
   * </pre>
   *
   * <code>int32 latitude = 1;</code>
   * @return The latitude.
   */
  int getLatitude();

  /**
   * <pre>
   * 纬度
   * </pre>
   *
   * <code>int32 longitude = 2;</code>
   * @return The longitude.
   */
  int getLongitude();
}
