// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

package com.dj.grpc.routeguide;

public interface RouteSummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:routeguide.RouteSummary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 路线上点的个数
   * </pre>
   *
   * <code>int32 point_count = 1;</code>
   * @return The pointCount.
   */
  int getPointCount();

  /**
   * <pre>
   *  路线上特性的个数
   * </pre>
   *
   * <code>int32 feature_count = 2;</code>
   * @return The featureCount.
   */
  int getFeatureCount();

  /**
   * <pre>
   * 距离
   * </pre>
   *
   * <code>int32 distance = 3;</code>
   * @return The distance.
   */
  int getDistance();

  /**
   * <pre>
   * 花费的时间
   * </pre>
   *
   * <code>int32 elapsed_time = 4;</code>
   * @return The elapsedTime.
   */
  int getElapsedTime();
}
