// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: route_guide.proto

package com.dj.grpc.routeguide;

public interface RouteNoteOrBuilder extends
    // @@protoc_insertion_point(interface_extends:routeguide.RouteNote)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.routeguide.Point location = 1;</code>
   * @return Whether the location field is set.
   */
  boolean hasLocation();
  /**
   * <code>.routeguide.Point location = 1;</code>
   * @return The location.
   */
  Point getLocation();
  /**
   * <code>.routeguide.Point location = 1;</code>
   */
  PointOrBuilder getLocationOrBuilder();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
