// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.dj.hello;

public final class HelloProto {
  private HelloProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hello_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hello_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hello_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hello_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013hello.proto\022\005hello\"\032\n\007Request\022\017\n\007messa" +
      "ge\030\001 \001(\t\"\033\n\010Response\022\017\n\007message\030\001 \001(\t2\344\001" +
      "\n\014HelloService\022*\n\005Hello\022\016.hello.Request\032" +
      "\017.hello.Response\"\000\0222\n\013HelloStream\022\016.hell" +
      "o.Request\032\017.hello.Response\"\0000\001\0228\n\021HelloS" +
      "ingleStream\022\016.hello.Request\032\017.hello.Resp" +
      "onse\"\000(\001\022:\n\021HelloDoubleStream\022\016.hello.Re" +
      "quest\032\017.hello.Response\"\000(\0010\001B\"\n\014com.dj.h" +
      "elloB\nHelloProtoP\001\242\002\003HELb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_hello_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hello_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hello_Request_descriptor,
        new String[] { "Message", });
    internal_static_hello_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hello_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hello_Response_descriptor,
        new String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
