// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.dj.hello;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hello.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
