server:
  port: 10010
spring:
  main:
    web-application-type: reactive
  application:
    name: dj-gateway
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: SZ #配置集群名称，也就是机房位置
        namespace: 590ec80f-7690-4899-8954-83f6f97fd8d6 #命名空间：相同命名空间的服务才可以访问
    gateway:
      routes:
        - id: dj-portal
          uri: lb://djportal
          predicates:
            - Path=/portal/**
          filters:
            - AddRequestHeader=jiangjie, hahahahah1111
      default-filters:
        - AddRequestHeader=jiangjie, hahahahah2222